# Generated by Django 4.0.3 on 2022-04-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
