# Generated by Django 4.0.3 on 2022-04-14 05:01

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='profilepic',
            field=models.ImageField(blank=True, default='default/default_profile_400x400.png', upload_to=register.models.image_path, verbose_name='Foto de perfil'),
        ),
        migrations.DeleteModel(
            name='Report_item',
        ),
    ]
