# Generated by Django 4.0.3 on 2022-04-11 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_rename_nome_usuario_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='O tamanho do nome tem que ser entre 4 e 25', regex='^.{4,25}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='O tamanho do nome tem que ser entre 4 e 25', regex='^.{4,25}$')]),
        ),
    ]
