# Generated by Django 4.0.3 on 2022-04-26 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_usuario_profilepic_delete_report_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='date_of_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='usuario',
            name='followersN',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='followingN',
            field=models.IntegerField(default=0),
        ),
    ]
