# Generated by Django 4.0.3 on 2022-04-26 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='publishDate',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='19:46'),
        ),
    ]
