# Generated by Django 4.0.3 on 2022-04-13 05:41

from django.db import migrations, models
import editprofile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.ImageField(blank=True, upload_to=None, validators=[editprofile.models.validate_profilepic_size], verbose_name='Foto de perfil')),
            ],
        ),
    ]
