# Generated by Django 4.0.3 on 2022-04-13 05:45

from django.db import migrations, models
import editprofile.models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to=register.models.image_path, validators=[editprofile.models.validate_profilepic_size], verbose_name='Foto de perfil'),
        ),
    ]
