# Generated by Django 4.0.5 on 2022-06-26 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_messages_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
