# Generated by Django 4.0.3 on 2022-05-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=280)),
                ('tweetAuthor', models.IntegerField()),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('publishDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
