# Generated by Django 4.0.5 on 2022-06-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_replys_likes_remove_tweet_likes_tweet_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='likec',
            field=models.IntegerField(default=0),
        ),
    ]
