# Generated by Django 4.0.5 on 2022-06-26 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_tweet_likec'),
    ]

    operations = [
        migrations.AddField(
            model_name='replys',
            name='likec',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='replys',
            name='likes',
        ),
        migrations.AddField(
            model_name='replys',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likesr', to=settings.AUTH_USER_MODEL),
        ),
    ]
