# Generated by Django 4.0.3 on 2022-08-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_replys_likec_remove_replys_likes_replys_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='mentionlink',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
