# Generated by Django 4.0.3 on 2022-08-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tweet_mentionlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='linkzaocarai',
            field=models.CharField(default='a', max_length=250),
            preserve_default=False,
        ),
    ]
