# Generated by Django 4.0.5 on 2022-06-26 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='publishDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
