# Generated by Django 4.0.5 on 2022-06-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='value',
        ),
        migrations.RemoveField(
            model_name='replys',
            name='likes',
        ),
        migrations.AddField(
            model_name='replys',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
