# Generated by Django 4.0.3 on 2022-05-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_like_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
