# Generated by Django 4.0.3 on 2022-05-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_tweet_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweetLink',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
