# Generated by Django 4.0.3 on 2022-05-01 23:59

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_tweet_tweetlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='replys',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.models.image_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])]),
        ),
    ]
