# Generated by Django 4.0.3 on 2022-05-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_replys_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replys',
            name='body',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
