# Generated by Django 4.0.3 on 2022-05-02 01:07

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_replys_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='replys',
            name='replyLink',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='replys',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.models.image_path2, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])]),
        ),
    ]
