# Generated by Django 4.0.3 on 2022-05-02 01:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_replys_replylink_alter_replys_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='replys',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='replyLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
