# Generated by Django 4.0.3 on 2022-05-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_replys_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='replysC',
            field=models.IntegerField(default=0),
        ),
    ]
