# Generated by Django 4.0.3 on 2022-05-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_tweet_replysc'),
    ]

    operations = [
        migrations.AddField(
            model_name='replys',
            name='replysC',
            field=models.IntegerField(default=0),
        ),
    ]
