# Generated by Django 4.0.3 on 2022-05-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
