# Generated by Django 4.0.3 on 2022-05-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_usuario_is_authenticated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_authenticated',
            new_name='isAuthenticated',
        ),
    ]
