# Generated by Django 4.0.3 on 2022-04-27 07:57

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_usuario_date_of_creation_usuario_followersn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='profilepic',
            field=models.ImageField(blank=True, default='default/default_profile_400x400.png', upload_to=register.models.image_path, validators=[register.models.Usuario.validate_profilepic_size], verbose_name='Foto de perfil'),
        ),
    ]
