# Generated by Django 4.0.3 on 2022-05-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_usuario_name_alter_usuario_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='followersN',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='followingN',
            new_name='following',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tweetsNumber',
            field=models.IntegerField(default=0),
        ),
    ]
