# Generated by Django 4.0.4 on 2022-06-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_rename_followersn_usuario_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usernameinsensitive',
            field=models.CharField(max_length=25, verbose_name='Nome de usuário'),
        ),
    ]
