# Generated by Django 4.0.4 on 2022-06-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_usuario_usernameinsensitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='saveditems',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
