# Generated by Django 4.0.4 on 2022-06-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_usuario_saveditems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='saveditems',
            new_name='savedsaitems',
        ),
    ]
