# Generated by Django 4.0.4 on 2022-06-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_rename_saveditems_usuario_savedsaitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='savedsaitems',
        ),
    ]
